source 'https://github.com/CocoaPods/Specs.git'

target 'PilightKit', :exclusive => true do
  pod "PilightKit", :path => "../"
end

target 'Tests', :exclusive => true do
  pod "PilightKit", :path => "../"

  
end
